version: '3.7'
networks:
  dravelops:
    name: bw_network
services:
  otp:
    build: .
    image: blackforestsolutions/dravelopsopentripplanner:latest
    volumes:
      - ./graphs:/var/otp/graphs
    environment:
      - JAVA_OPTIONS=-Xmx2G
    command:
      [
          '--server',
          '--analyst',
          '--autoScan',
          '--insecure',
          '--verbose',
          '--port',
          '8089',
          '--securePort',
          '8090'
      ]
    networks:
      - dravelops