version: '3.7'

services:
  otp:
    build: .
    image: blackforestsolutions/dravelopsopentripplanner:latest
    ports:
      - 8089:8089
    volumes:
      - ./graphs:/var/otp/graphs
    environment:
      - JAVA_OPTIONS=-Xmx4G
    command:
      [
          '--server',
          '--analyst',
          '--autoScan',
          '--insecure',
          '--verbose',
          '--port',
          '8089',
          '--securePort',
          '8090'
      ]