version: '3.7'
networks:
  dravelops:
    name: hvv_network
services:
  otp-fast:
    image: blackforestsolutions/dravelopsopentripplanner:hvv-fast-0.1.1
    environment:
      - DEPLOY_FOLDER_RUN_TIME=hvv-fast
      - JAVA_OPTIONS=-Xmx3G
      - PORT=9000
      - SECURE_PORT=9001
    networks:
      - dravelops
    ports:
      - 9000:9000