version: '3.7'
networks:
  dravelops:
    name: bw_network
services:
  otp-slow:
    image: blackforestsolutions/dravelopsopentripplanner:bw-slow-1.0.0
    environment:
      - DEPLOY_FOLDER=bw-slow
      - JAVA_OPTIONS=-Xmx2G
      - PORT=9002
      - SECURE_PORT=9003
    networks:
      - dravelops