version: '3.7'
networks:
  dravelops:
    name: sbg_network
services:
  otp-fast:
    image: blackforestsolutions/dravelopsopentripplanner:sbg-fast-0.0.2
    environment:
      - DEPLOY_FOLDER_RUN_TIME=sbg-fast
      - JAVA_OPTIONS=-Xmx2G
      - PORT=9000
      - SECURE_PORT=9001
    networks:
      - dravelops
    ports:
      - 9000:9000