version: '3.7'
networks:
  dravelops:
    name: bw_network
services:
  otp-fast:
    image: blackforestsolutions/dravelopsopentripplanner:bw-fast-1.0.0
    environment:
      - DEPLOY_FOLDER=bw-fast
      - JAVA_OPTIONS=-Xmx20G
      - PORT=9000
      - SECURE_PORT=9001
    networks:
      - dravelops